Title: Coleman Human Factors Engineering
Description: Coleman Human Factors Services 
theme: jekyll-theme-cayman
Author: Brian S. Coleman, M.A., AHFP
linkedin_username: https://www.linkedin.com/in/brian-s-coleman/
