Author: Brian S. Coleman, M.A., AHFP
title: Coleman Human Factors Engineering
theme: jekyll-theme-cayman
url: /https://coleman-human-factors-engineering.github.io/Services/
baseurl: "" 
github_username: Coleman-Human-Factors-Engineering
linkedin_username: https://www.linkedin.com/in/brian-s-coleman/
navigation:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Projects
    link: /projects/
  - name: Blog
    link: /blog/
  - name: Contact
    link: /contact/
